# Generated by Django 4.2 on 2024-09-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_id', models.IntegerField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15, null=True)),
                ('diseases', models.TextField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vital_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('heart_Rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('body_mass_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('patient', models.ManyToManyField(to='vital_signs.patient')),
            ],
        ),
    ]
