# Generated by Django 4.2 on 2024-10-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0002_rename_blood_pressure_vital_signs_diastolic_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital_signs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vital_signs', to='vital_signs.patient'),
        ),
    ]
