# Generated by Django 4.2 on 2024-10-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0003_alter_vital_signs_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital_signs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vital_signs.patient'),
        ),
    ]
