# Generated by Django 4.2 on 2024-10-10 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vital_signs', '0004_alter_vital_signs_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital_signs',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
